### PR TITLE
Allow Customization of the Element Header

### PR DESCRIPTION
**Pull request by owaits**
HeaderClass expands on the HeaderStyle attribute of an element to allow you to define a custom class to be applied to the headers as well as changing the style.

You can now add a Header tag to either the Element or Grid that allows you to insert custom markup that is used instead of the default header markup. When this markup is used the Header level and alignment are ignored. This means the header does not just have to contain a title but can have varying test, images icons etc.

### CODE REVIEW

**Comment by stefanloerwald** [comment]
Hi @owaits,

Same here: this looks good, except for the .gitignore file.

Thanks
Stefan

**Comment by white-jacob-dev** [comment]
I seem to be getting the following error when I use @owaits changes here, says the issue is from Grid/Element.razor Line 15. I'm using the Grid snippet from the main project readme incase that's of any help.
Screenshot 2022-11-15 at 2 17 49 PM

**Comment by owaits** [comment]
> I seem to be getting the following error when I use @owaits changes here, says the issue is from Grid/Element.razor Line 15. I'm using the Grid snippet from the main project readme incase that's of any help. Screenshot 2022-11-15 at 2 17 49 PM

I have tried running the test project and selecting the Grid example page but I am not seeing this error. I also pasted the example grid code bellow, is this what you where referring to?

```
<Grid RowGap="1em" ColumnGap="1em">
    <RowDefinition Height="1fr" />
    <RowDefinition Height="1fr" />
    <ColumnDefinition Width="auto" />
    <ColumnDefinition Width="auto" />
    <Element Column="0" Row="0">
        <div style="background-color: purple; min-width: 2em; min-height: 2em"></div>
    </Element>
    <Element Column="0" Row="1">
        <div style="background-color: pink; min-width: 2em; min-height: 2em"></div>
    </Element>
    <Element Column="1" Row="0">
        <div style="background-color: gray; min-width: 2em; min-height: 2em"></div>
    </Element>
    <Element Column="1" Row="1">
        <div style="background-color: green; min-width: 2em; min-height: 2em"></div>
    </Element>
</Grid>
```

to the Grid example but that seemed to work too.

The error refers to this line

`var padding_bottom_s = padding_bottom.ToString(CultureInfo.InvariantCulture) + "%";`

which I do not believe I have changed so I am a little confused why this is not working. 

Are you able to give me some more info or repro steps so I can try and resolve this?

**Comment by white-jacob-dev** [comment]
> > I seem to be getting the following error when I use @owaits changes here, says the issue is from Grid/Element.razor Line 15. I'm using the Grid snippet from the main project readme incase that's of any help. Screenshot 2022-11-15 at 2 17 49 PM
> 
> I have tried running the test project and selecting the Grid example page but I am not seeing this error. I also pasted the example grid code bellow, is this what you where referring to?
> 
> ```
> <Grid RowGap="1em" ColumnGap="1em">
>     <RowDefinition Height="1fr" />
>     <RowDefinition Height="1fr" />
>     <ColumnDefinition Width="auto" />
>     <ColumnDefinition Width="auto" />
>     <Element Column="0" Row="0">
>         <div style="background-color: purple; min-width: 2em; min-height: 2em"></div>
>     </Element>
>     <Element Column="0" Row="1">
>         <div style="background-color: pink; min-width: 2em; min-height: 2em"></div>
>     </Element>
>     <Element Column="1" Row="0">
>         <div style="background-color: gray; min-width: 2em; min-height: 2em"></div>
>     </Element>
>     <Element Column="1" Row="1">
>         <div style="background-color: green; min-width: 2em; min-height: 2em"></div>
>     </Element>
> </Grid>
> ```
> 
> to the Grid example but that seemed to work too.
> 
> The error refers to this line
> 
> `var padding_bottom_s = padding_bottom.ToString(CultureInfo.InvariantCulture) + "%";`
> 
> which I do not believe I have changed so I am a little confused why this is not working.
> 
> Are you able to give me some more info or repro steps so I can try and resolve this?

It looks like the error is actually referring to the line following, which is: 
`<div class="eg-elc @Grid.ElementClass @additional_class" style="@Grid.ElementStyle; @additional_style; @area @column @row padding-bottom: @padding_bottom_s; " @attributes='AdditionalAttributes?.Where(kv => kv.Key != "style" && kv.Key != "class")' @ref="ElementContainer">`

I created a new Blazor WASM project and added the 'Grid' folder from this repo into that project and updated some dependencies. Everything was working using the snippet you posted above, until I added in your changes manually. It could well be an issue on my end, but given that it was working fine before I added the changes, I just wanted to make sure. Great update regardless!

**Comment by owaits** [comment]
@white-jacob-dev its strange because the line of code seeming to be the issue can only be reached if the Aspect Ratio is not null yet the snippet of code does not set the aspect ratio. I would be happy to take a look at your test project if you want. Maybe you could clone my repo and run the official test projects to see if you experience any issues with them.

**Comment by white-jacob-dev** [comment]
@owaits I'm not getting a crash when cloning your branch, so I'm assuming it's something on my end, no worries. One question though, where are you defining the Header tag in your code? I'm using it inside of an element as `<Header>Some markup</Header>,` but the element is no longer draggable afterwards.

**Comment by owaits** [comment]
It should allow you to.put the header tag either on the grid or element. You need to be careful though that the contents do not block the mouse events propogating to the drag drop handlers. In my case I just put an icon and div inside the header. I will post an example tomorrow for you.

**Comment by stefanloerwald** [comment]
Hi @owaits,

I think a demo page would be a great addition and could help @white-jacob-dev to identify the issue they're experiencing.

Thanks
Stefan

**Comment by owaits** [comment]
@stefanloerwald I have added a demo page for custom headers that hopefully demonstrates why custom headers can be quite powerful. Let me know if you require anything further for this PR.

**Comment by stefanloerwald** [comment]
Hi @owaits,

Thanks for your patience here ;-) I just played with your demo page and it looks beautiful! I'll merge it ASAP.

Thanks for your contribution.
Stefan

**Pull request merged**
